### ISSUE TITLE
Decryptor should check input length after decoding

### ISSUE THREAD

**Issue by aayla-secura** [JamesMGreene/node-aes256#1]
The length of the input string is ensured to be 17 bytes or more, otherwise it would either be invalid (<16) or always decrypt to empty string (=16). But the check is made on the base64 encoded input, which is longer than the decoded string. Just move the check a few lines down, after base64 decoding. (I submitted a pull request, but I think I messed up the commit summary, cause it didn't link to the issue)

**Comment by JamesMGreene** [comment]
Published as `v1.0.3`.
